### ISSUE TITLE
APK 安装失败

### ISSUE THREAD

**Issue by CherryLover** [Bakumon/StatusLayoutManager#1]
我将 StatusLayoutManager.apk 下载之后，无论是通过文件发送到 Android 手机还是 ADB 安装都失败了。ADB 安装失败提示 `INSTALL_FAILED_TEST_ONLY`。

**Comment by Bakumon** [comment]
很奇怪的问题，用android studio run 生成的 debug 版和 release 版 apk，通过 adb 安装都会报这个错。只有手动选择签名文件的方式打包才能正常安装。

https://stackoverflow.com/questions/25274296/adb-install-fails-with-install-failed-test-only

这个链接是解决 `INSTALL_FAILED_TEST_ONLY` 的方案，但是都不可行。

**我更新了[app-release.apk](https://github.com/Bakumon/StatusLayoutManager/raw/master/apk/app-release.apk)**，可以正常安装。

**Comment by CherryLover** [comment]
adb install -t StatusLayoutManager.apk 是可行得，在我测试的机器上。
