### ISSUE TITLE
好像用SmartRefreshLayout后用你这个不起作用

### ISSUE THREAD

**Issue by qiushui95** [Bakumon/StatusLayoutManager#3]
https://github.com/scwang90/SmartRefreshLayout

**Comment by Bakumon** [comment]
怎么使用的，麻烦贴出来

**Comment by skyCracks** [comment]
JAVA : 
StatusLayoutManager statusLayoutManager = new StatusLayoutManager.Builder(RecyclerView);

XML:
 <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/layout_refresh"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recycler_friend"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginTop="10dp"
            android:background="@color/white"
            android:overScrollMode="never" />

    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

加载除showSuccessLayout之外的showXXX方法都为一片空白

**Comment by hudan2714** [comment]
解决了吗？

**Comment by xicong** [comment]
我也遇到了，你怎么解决的啊

**Comment by dreamerlxb** [comment]
再添加一层布局可以解决
```java
<com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/doc_srl"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <FrameLayout
            android:id="@+id/status_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent">


            <android.support.v7.widget.RecyclerView
                android:id="@+id/doc_rv"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

        </FrameLayout>
    </com.scwang.smartrefresh.layout.SmartRefreshLayout>
```

**Comment by HeroYiu** [comment]
new StatusLayoutManager.Builder(doc_srl); 直接把SmartRefreshLayout作为内容view应该就没你说的问题了 @skyCracks

**Comment by ZhongJieX** [comment]
我测到过这个bug SmartRefreshLayout 有一个CircleImageView 和 一个自己加的内容布局 每次下拉刷新会 CircleImageView 和 自己加的内容布局的下标发生改变 比如CircleImageView 的index=0;刷新后就变1了 个自己加的内容布局的index=0了 因为StatusLayout会先遍历你要替换布局的下标，当你要替换的布局是SmartRefreshLayout 里面的内容布局的时候 就会出现把CircleImageView 替换的问题

**Comment by hudan2714** [comment]
增加了一层，都不显示空页面了，直接白屏？？？有遇到 过吗？
`   <com.szy.ui.uibase.widget.refreshlayout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <FrameLayout
            android:id="@+id/status_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recycleView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
           />
        </FrameLayout>
    </com.szy.ui.uibase.widget.refreshlayout.SmartRefreshLayout>`

**Comment by AriesHoo** [comment]
不将SmartRefreshLayout作为Activity/Fragment根布局可以解决

**Comment by hudan2714** [comment]
这是支持下拉刷新和上拉加载更多，目前只能将refreshLayout作为内容布局，但这样就没有下拉操作了，使用status_layout或recyclerview都无法显示空布局等

<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center_horizontal"
    android:orientation="vertical"
    >

    <SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        >

        <ClassicsHeader
            android:layout_width="match_parent"
            android:layout_height="40dp"
            app:srlClassicsSpinnerStyle="FixedBehind"
            app:srlDrawableArrowSize="20dp"
            app:srlDrawableMarginRight="10dp"
            app:srlDrawableProgressSize="15dp"
            app:srlEnableLastTime="true"
            app:srlFinishDuration="500"
            app:srlTextSizeTime="7dp"
            app:srlTextSizeTitle="10sp"
            app:srlTextTimeMarginTop="2dp"/>
<FrameLayout
            android:id="@+id/status_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            />
   </FrameLayout>
        <ClassicsFooter
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:srlClassicsSpinnerStyle="Translate"
            />
    </SmartRefreshLayout>
</LinearLayout>
