### ISSUE TITLE
会出现id替换不显示的问题

### ISSUE THREAD

**Issue by hudan2714** [Bakumon/StatusLayoutManager#5]
设置emptyLayout时，设置text和image，会不显示

**Comment by Bakumon** [comment]
show your code

**Comment by hudan2714** [comment]
这是支持下拉刷新和上拉加载更多，目前只能将refreshLayout作为内容布局，但这样就没有下拉操作了，使用status_layout或recyclerview都无法显示空布局等

<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center_horizontal"
    android:orientation="vertical"
    >

    <SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        >

        <ClassicsHeader
            android:layout_width="match_parent"
            android:layout_height="40dp"
            app:srlClassicsSpinnerStyle="FixedBehind"
            app:srlDrawableArrowSize="20dp"
            app:srlDrawableMarginRight="10dp"
            app:srlDrawableProgressSize="15dp"
            app:srlEnableLastTime="true"
            app:srlFinishDuration="500"
            app:srlTextSizeTime="7dp"
            app:srlTextSizeTitle="10sp"
            app:srlTextTimeMarginTop="2dp"/>
<FrameLayout
            android:id="@+id/status_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            />
   </FrameLayout>
        <ClassicsFooter
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:srlClassicsSpinnerStyle="Translate"
            />
    </SmartRefreshLayout>
</LinearLayout>

**Comment by Bakumon** [comment]
#3
