### ISSUE TITLE
自定义布局，background属性无效

### ISSUE THREAD

**Issue by Xbigfat** [Bakumon/StatusLayoutManager#6]
作者你好！使用 .setEmptyLayout(R.layout.custom_layout) 时，自定义的layout中 background 属性无效，请帮看看是哪里的问题呢？
XML：
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/orange"
    android:gravity="center"
    android:orientation="vertical">

    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/ic_no_data" />

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/no_data_tips"
        android:textColor="@color/primary"
        android:textSize="16sp" />

</LinearLayout>`

这里设置了橘色的背景布局，但在App中不是橘色。

**Comment by Bakumon** [comment]
@Xbigfat 
### 1. Builder有一个统一设置背景色的方法：

```
Builder#setDefaultLayoutsBackgroundColor(int color)
```
这个方法会**统一**设置 `Loading` 、`Empty、 `Error`  布局的背景色。

### 2. 可以通过覆盖 color 来设置背景颜色
[color.xml](https://github.com/Bakumon/StatusLayoutManager/blob/master/library/src/main/res/values/colors.xml)，覆盖 `status_layout_background_color ` 

---

以上两种方法，都会统一改变三种内置布局的颜色（自定义布局不受影响），这是一个不好的设计，我会改掉，然后发新版。

**Comment by Xbigfat** [comment]
解决问题！
我看了此方法，但是我以为该方法仅针对于默认布局，并未想到该方法亦会影响到自定义布局。
感谢说明。

**Comment by Bakumon** [comment]
@Xbigfat 问题已经解决

升级 1.0.3 版本，下面方法只会改变默认布局的背景色。

```
Builder#setDefaultLayoutsBackgroundColor(int color)
```
