### ISSUE TITLE
setDefaultLayoutsBackgroundColor不起作用

### ISSUE THREAD

**Issue by puyunfeng** [Bakumon/StatusLayoutManager#9]
if (this.emptyLayout == null) {
            this.emptyLayout = this.inflate(this.emptyLayoutID);
        } else {
            this.emptyLayout.setBackgroundColor(this.defaultBackgroundColor);
        }

so 当我想改变背景色的时候
必须这样
                statusLayoutManager.getEmptyLayout();
                statusLayoutManager.showEmptyLayout();

**Comment by Bakumon** [comment]
感谢反馈，问题确实存在，已经修改
新版本：1.0.4
